# Generated by Django 5.0.1 on 2024-01-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_manager', '0003_alter_gearlistitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
