# Generated by Django 5.0.1 on 2024-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_manager', '0002_gearlistitem_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearlistitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
