# Generated by Django 5.0.1 on 2024-02-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_manager', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearlistitem',
            name='category',
        ),
    ]
