# Generated by Django 5.0.1 on 2024-02-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_manager', '0005_remove_gearlistitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gearlist',
            name='items',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_list',
            field=models.ManyToManyField(blank=True, to='gear_manager.gearlist'),
        ),
        migrations.AddField(
            model_name='gearlist',
            name='categories',
            field=models.ManyToManyField(to='gear_manager.category'),
        ),
    ]
